esphome:
  name: gate
  friendly_name: Gate

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:


ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password:  !secret wifi_password

web_server:

external_components:
  - source: components

uart:
  tx_pin: GPIO32
  rx_pin: GPIO33
  baud_rate: 19200
  parity: none
  stop_bits: 1

bus_t4:
 id: bus
 
cover:
- platform: bus_t4
  name: None
  id: gate

